### ISSUE TITLE
Overriding "logger config template" does not work as expected

### ISSUE THREAD

**Issue by christianmasopust** [ansible-middleware/amq#112]
##### SUMMARY
In our setup we plan to forward the Artemis logs to Elasticsearch. To enable that, we would need to use our own log4j2.properties or logging.properties template.

Our idea was to use the existing option (_amq_broker_logger_config_template_) to override this template, but it doesn't work as expected, it is only there for selecting the right logger config file:
```yaml
amq_broker_logger_config_template: "{{ 'log4j2.properties' if amq_broker_version is version_compare('7.11.0', '>=') else 'logging.properties' }}"
```

And it's then used in the configuration of the broker as:
```yaml
  ansible.builtin.template:
    src: "{{ amq_broker_logger_config_template }}.j2"
    dest: "{{ amq_broker.instance_home }}/etc/{{ amq_broker_logger_config_template }}"
```
Which, of course, will not work when _amq_broker_logger_config_template_ is a path.

Maybe the intention for _amq_broker_logger_config_template_ was not to allow the user to override the template, so you may this not consider as a bug and more as a feature request...

##### ISSUE TYPE
 - Bug Report

##### EXPECTED RESULTS
Having the possibility to use our own template for the broker logging configuration similar as it is already implemented for the systemd service.

Maybe a possible solution would be to not completely override the template but have the option to specify a "template path" and keep the decision which template (logging or log4j2) up to the role.

**Comment by christianmasopust** [comment]
Yes, that may be a working fix. But then we would have to take care about which Artemis version we are using (to decide whether we have to use the previous logging.properties or the newer log4j2.properties template).

When adding something like "template_location" at the source (which by default is an empty string), then to role still would decide which "type" of logging template it has to be used and the location would just tell it where to find it.

What I mean would be:
```yaml
  ansible.builtin.template:
    src: "{{ template_location }}{{ amq_broker_logger_config_template }}.j2"
    dest: "{{ amq_broker.instance_home }}/etc/{{ amq_broker_logger_config_template }}"
```

Or do you think that may cause other issues?
