### ISSUE TITLE
Xinput configuration import into broker.xml

### ISSUE THREAD

**Issue by guidograzioli** [ansible-middleware/amq#122]
##### SUMMARY

Allow certain configurations to be kept in a (or 1+ modularized) separate file(s), imported via XInclude [1]

[1] https://activemq.apache.org/components/artemis/documentation/latest/configuration-index.html#modularising-broker-xml

##### ISSUE TYPE
 - Feature Idea

**Comment by herbertkb** [comment]
One way we did this is to have a boolean variable to toggle modularization, and put the current behavior in a block for when it's false, and in a block for when it's true:

```yaml
- name: Create security-settings file
  ansible.builtin.template:
    src: security_settings.modular.xml.j2
    dest: "{{ amq_broker_dest + '/' + amq_broker_instance_name }}/etc/security-settings.xml"

- name: Remove security-settings element from broker.xml
  redhat.runtimes_common.xml:
    path: "{{ amq_broker_dest + '/' + amq_broker_instance_name }}/etc/broker.xml"
    xpath: /conf:configuration/core:core/core:security-settings
    state: absent
    namespaces:
      conf: urn:activemq
      core: urn:activemq:core 

- name: Import security-settings file 
  redhat.runtimes_common.xml:
    path: "{{ amq_broker_dest + '/' + amq_broker_instance_name }}/etc/broker.xml"
    xpath: /conf:configuration/core:core/xi:include[@href='{{ amq_broker_dest + '/' + amq_broker_instance_name }}/etc/security-settings.xml']
    namespaces:
      xi: http://www.w3.org/2001/XInclude
      conf: urn:activemq
      core: urn:activemq:core
    pretty_print: true

```

Where the `security_settings.modular.xml.j2` is

```jinja2
<?xml version="1.0" encoding="utf-8"?>
<security-settings xmlns="urn:activemq:core">
{% for securitySetting in securitySettings %}
    <security-setting match="{{ securitySetting.match }}">
{% for config in securitySetting.permissions  %}
        <permission type="{{ config.permission }}" roles="{{ config.roles | join(',') }}"/>
{% endfor %}
    </security-setting>
{% endfor %}
</security-settings>
```
