### ISSUE TITLE
Allow more granular configuration of console access (management.xml)

### ISSUE THREAD

**Issue by cmasopust** [ansible-middleware/amq#144]
##### SUMMARY
Currently we only can specify a list of roles in amq_broker_hawtio_role which then gets access defined in amq_broker_management_access_default and amq_broker_management_access_domains, so all used roles will have the same type of access.

A more flexible way of configuring access in management.xml would be very welcome for, e.g., configuring additional read-only roles, etc.  Could imagine to configure the access like:

```
console_access:
  - roles: "role1,role2,..."
    - domain1: "list,get,..."
    - domain2: "..."
  - roles: "roleA, roleB,..."
    - domain1: "..."
...
```

##### ISSUE TYPE
 - Feature Idea
