### ISSUE TITLE
amq_broker_uninstall doesnt always stop the broker

### ISSUE THREAD

**Issue by garethahealy** [ansible-middleware/amq#184]
##### SUMMARY
I've noticed that sometimes, amq_broker_uninstall doesn't stop the process which means the below task fails.

```
TASK [redhat.amq_broker.amq_broker_uninstall : Delete service user] *******************************************************************************************************************************************************************************
fatal: [ip-11-0-1-001.eu-west-2.compute.internal]: FAILED! => {"changed": false, "msg": "userdel: user amq-broker is currently used by process 21295\n", "name": "amq-broker", "rc": 8}
```

If I jump onto the box and manually stop the service, I can then re-run amq_broker_uninstall successfully.

**Comment by garethahealy** [comment]
inventory:

```
amq1:
  hosts:
    ip-11-0-1-001.eu-west-2.compute.internal:
      amq_broker_instance_name: amq1
```

deploy playbook
```
---
- name: Deploy AMQ single broker with custom broker.xml
  hosts: amq1
  gather_facts: true
  vars:
    # SSH key
    ansible_ssh_private_key_file: ec2_keypair.pem
    # Broker template
    amq_broker_config_override_template: templates/broker.xml.j2
    # HACK: Allows console
    amq_broker_cors_strict_checking: false
  roles:
    - redhat.amq_broker.amq_broker
```

uninstall playbook
```
---
- name: Remove any AMQ installations
  hosts: all
  gather_facts: true
  vars:
    # SSH key
    ansible_ssh_private_key_file: ec2_keypair.pem
    # AWS
    region: "eu-west-2"
  roles:
    - redhat.amq_broker.amq_broker_uninstall
```

**Comment by garethahealy** [comment]
log out shows:

```
TASK [redhat.amq_broker.amq_broker_uninstall : Disable and stop instance amq1 for amq_broker service] *********************************************************************************************************************************************
skipping: [ip-11-0-1-001.eu-west-2.compute.internal]
```

why wouldn't the below be true?
- https://github.com/ansible-middleware/amq/blob/main/roles/activemq_uninstall/tasks/systemd.yml#L11C49-L11C62

**Comment by guidograzioli** [comment]
Weird, I am baffled; will try to reproduce (if you run uninstall again, can you remember ANSIBLE_VERBOSITY=3 ? that would help)

**Comment by guidograzioli** [comment]
Maybe it failed to stop? or the playbook reached the user deletion before it terminated. I'll add a stop check after the systemd task, but I am also tempted to add a PostStopExec to the systemd unit.

**Comment by garethahealy** [comment]
Solved it. Invalid config on my side. In my inventory file I had:

```
all:
  hosts:
    amq1:
      ansible_host: ip-11-0-1-163.eu-west-2.compute.internal

amq1:
  hosts:
    ip-11-0-1-163.eu-west-2.compute.internal:
      amq_broker_instance_name: amq1
```

I noticed in the logs, that sometimes it would use `amq1` and other times, `amq-broker` (the default). So guessing the above confused installer, so the uninstaller didn't really know what to do either.

Will 100% confirm tomorrow, but just a quick test, I am 99% sure, as I removed `all` and it installed/uninstalled correctly and I am only seeing this on this playbook
