### ISSUE TITLE
activemq_mask_password is ignored

### ISSUE THREAD

**Issue by AWD09** [ansible-middleware/amq#189]
##### SUMMARY
I set **activemq_mask_password** to **false** because my user passwords are already encrypted.  
Though in etc/artemis-users.role, the encrypted password are changed.  

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible [core 2.11.12]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myuser/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/myuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/myuser/.local/bin/ansible
  python version = 3.6.8 (default, Sep  9 2024, 06:12:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```
/home/myuser/.ansible/collections/ansible_collections
Collection                   Version
---------------------------- -------
ansible.posix                1.5.4
ansible.utils                5.1.0
middleware_automation.amq    1.3.10
middleware_automation.common 1.1.4
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Install AMQ
  hosts: all
  vars:
    amq_broker_mask_password: false
    amq_broker_users:
      - user: test-user
        password: ENC(1024:0E58900B956BBEED271D71CA393BF7C893853EE94491F391D5F0CB45C18E1FB5:3587268B3DF2287A486301ED900C599AFD549955A4A9D08A743B5E9D90F2DFCF425B654B012DD1474DEBCBB97D9242990C7D35E7EF74C4BC8607A526BCD43D03)
        roles: [ pub-user ]
    amq_broker_roles:
      - match: test.v1.#
        name: pub_user
        permissions: [ createAddress, createDurableQueue, createNonDurableQueue, deleteAddress, deleteDurableQueue, deleteNonDurableQueue, manage, send ]

  tasks:
  - name: Install ActiveMQ
    ansible.builtin.import_role:
      name: middleware_automation.amq.activemq
```

##### EXPECTED RESULTS

etc/artemis-user.properties should contain:
```
test-user = ENC(1024:0E58900B956BBEED271D71CA393BF7C893853EE94491F391D5F0CB45C18E1FB5:3587268B3DF2287A486301ED900C599AFD549955A4A9D08A743B5E9D90F2DFCF425B654B012DD1474DEBCBB97D9242990C7D35E7EF74C4BC8607A526BCD43D03)
```

##### ACTUAL RESULTS
etc/artemis-user.properties contains:
```
test-user = ENC(1024:1DE5CAE6A6040193B81BBC4159E1AE9BED605AC2230F9084121F38CE9E154D5F:92F855AE450B65DBB26E1F6D2AD61B3B64686F4BAFE75E7ED8AD204E5BDA8086930219F5CFBB6923FBD97C0E65BD4A9F1D304A7570F7893DFA897FEFF0B62E62)
```
