### ISSUE TITLE
Issue with restart handler

### ISSUE THREAD

**Issue by cmasopust** [ansible-middleware/amq#190]
##### SUMMARY
Restart handler results in error when `amq_broker_configuration_file_refresh_period` is defined via Jinja2.

We are defining `amq_broker_configuration_file_refresh_period` in such way:
```yaml
- set_fact:
     amq_broker_configuration_file_refresh_period: "{{ ... }}"
```
which makes `amq_broker_configuration_file_refresh_period` being of type `str`

I know, this may be special to our environment, but a simple fix/mitigation could be changing the when
condition for the restart handler.
```yaml
- name: "Restart handler"
  ansible.builtin.include_tasks: restart.yml
  when: amq_broker_configuration_file_refresh_period | int < 1
  listen: "restart amq_broker with no config refresh"
```

I also tried to set `jinja2_native=True` in my ansible.cfg but that lead then to lots of errors at "Set journal configuration", error were: 

> TypeError: Argument must be bytes or unicode, got 'int'

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.14.14]
  config file = /home/cmaso/.ansible.cfg
  configured module search path = ['/home/cmaso/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/cmaso/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, Jul  3 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
redhat.amq_broker                        2.2.5
```
