### ISSUE TITLE
"Get masked password for user" task takes more than 2 minutes per users after some iteration

### ISSUE THREAD

**Issue by AWD09** [ansible-middleware/amq#192]
##### SUMMARY
I have about 60 'amq_broker_users' users. The playbook takes more than 2 hours to run.
The issue is that the https://github.com/ansible-middleware/amq/blob/main/roles/activemq/tasks/mask_password.yml is masking the password for every user to check if it is still valid.  
The 12 first takes about 3 seconds each to be checked.
From the next one it takes between 2 and 3 minutes to process each one.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.11.12]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myuser/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/myuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/myuser/.local/bin/ansible
  python version = 3.6.8 (default, Sep  9 2024, 06:12:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```
Collection                   Version
---------------------------- -------
ansible.posix                1.5.4
ansible.utils                5.1.0
middleware_automation.amq    2.2.5
middleware_automation.common 1.1.4
```

##### STEPS TO REPRODUCE

```yaml
- name: Install AMQ
  hosts: all
  vars:
    amq_broker_version: 7.12.1
    amq_broker_mask_password: true
    amq_broker_users:
      - user: test-user1
        password: ENC(1024:0E58900B956BBEED271D71CA393BF7C893853EE94491F391D5F0CB45C18E1FB5:3587268B3DF2287A486301ED900C599AFD549955A4A9D08A743B5E9D90F2DFCF425B654B012DD1474DEBCBB97D9242990C7D35E7EF74C4BC8607A526BCD43D03)
        roles: [ pub-user ]
#ADD 59 more similar users here
    amq_broker_roles:
      - match: test.v1.#
        name: pub_user
        permissions: [ createAddress, createDurableQueue, createNonDurableQueue, deleteAddress, deleteDurableQueue, deleteNonDurableQueue, manage, send ]
  tasks:
#AMQ installation with Red Hat amq_broker playbook
  - name: Install AMQ
    ansible.builtin.import_role:
      name: redhat.amq_broker.amq_broker
    no_log: False
```

##### EXPECTED RESULTS

That running the activemq role takes a reasonable amount of time to run (<5 minutes).

##### ACTUAL RESULTS
The playbook runs for more than 2 hours.
