### ISSUE TITLE
Gather info module returns task skipped in case of CORS failure

### ISSUE THREAD

**Issue by guidograzioli** [ansible-middleware/amq#204]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.16.12
```

##### COLLECTION VERSION

```
n/a
```

##### STEPS TO REPRODUCE

```yaml
    - name: Populate activemq facts
      middleware_automation.amq.activemq_facts:
        base_url: https://localhost:8161
        auth_username: amq
        auth_password: amqbrokerpass
        validate_certs: false
        web_origin: 'this does not match the allowed origins in jolokia-access.xml'
```

##### EXPECTED RESULTS

Task returns an error and a meaning full error message

##### ACTUAL RESULTS

Task is skipped, likely causing a later failure for undefined variables.
