### ISSUE TITLE
user roles have to be unique

### ISSUE THREAD

**Issue by 4nt01ne** [ansible-middleware/amq#209]
##### SUMMARY

This is the issue solved by my PR https://github.com/ansible-middleware/amq/pull/208

We have more than 100 roles and about 60 users.
Same roles are allowed on multiple security-setting match.
If one role is configured more than once in the activemq_roles it is duplicated each time in artemis-roles.properties.

FYI: this PR is from my private account behind AWD09. We have migrated to GH Enterprise and I am not allowed to open issues or fork repos on my pro account anymore.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.11.12]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.6.8 (default, Sep  9 2024, 06:12:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```
Collection                   Version
---------------------------- -------
ansible.posix                1.5.4
ansible.utils                5.1.0
middleware_automation.amq    2.2.7
middleware_automation.common 1.1.4
```

##### STEPS TO REPRODUCE

```yaml
---

- name: reproduce roles generation
  hosts: localhost
  vars:
    amq_broker_users:
      - user: one
        password: abc
        roles: [ role_a ]
      - user: two
        password: abc
        roles: [ role_a, role_b ]
    amq_broker_roles:
      - match: a.queue.*
        name: role_a
        permissions: [ createAddress, createDurableQueue, createNonDurableQueue, deleteAddress, deleteDurableQueue, deleteNonDurableQueue, manage, send ]
      - match: an.other.queue.*
        name: role_b
        permissions: [ createAddress, createDurableQueue, createNonDurableQueue, deleteAddress, deleteDurableQueue, deleteNonDurableQueue, manage, send ]
      - match: a.last.queue.*
        name: role_a
        permissions: [ manage, send ]
  tasks:
    - name: Configure roles
      ansible.builtin.template:
        src: artemis-roles.properties.j2
        dest: artemis-roles.properties
```

##### EXPECTED RESULTS

artemis-roles.properties contains:
```
role_a=one,two
role_b=two
```

##### ACTUAL RESULTS

artemis-roles.properties contains:
```
role_a=one,two
role_b=two
role_a=one,two
```
