### ISSUE TITLE
Deployment failing when trying to deploy Apache Artemis with the Red Hat certified collection amq_broker

### ISSUE THREAD

**Issue by cmasopust** [ansible-middleware/amq#237]
##### SUMMARY
For a setup of an Apache Artemis broker I configured the following (using the Red Hat certified collection amq_broker):
```yaml
amq_broker_enable: false
amq_broker_version: 2.41.0
```
Version has been looked up at https://archive.apache.org/dist/activemq/activemq-artemis/

Running the deployment then gives errors when the role tries to download the `config_xsd` (from https://github.com/apache/amq_broker-artemis/raw/{{ amq_broker_version }}/artemis-server/src/main/resources/schema/artemis-configuration.xsd) and `server_xsd` (from https://github.com/apache/amq_broker-artemis/raw/{{ amq_broker_version }}/artemis-server/src/main/resources/schema/artemis-server.xsd)

Searching for project `amq_broker-artemis` at github failed, shouldn't it be `activemq-artemis` like it is in this collection ?

Looks like the definition of config_xsd and server_xsd in `vars/main.yml` is wrong in collection `redhat.amq_broker`

```yaml
### internal variables
amq_broker:  # noqa var-naming false positive
  home: "{{ amq_broker_installdir }}"
  user_home: "{{ amq_broker_service_user_home }}"
  version: "{{ amq_broker_version }}"
  download_url: "{{ amq_broker_download_url }}"
  bundle: "{{ amq_broker_archive }}"
  name: "{{ amq_broker_name }}"
  service_name: "{{ amq_broker_service_name }}"
  instance_name: "{{ amq_broker_instance_name }}"
  instance_home: "{{ amq_broker_dest }}/{{ amq_broker_instance_name }}"
  config_xsd: "https://github.com/apache/amq_broker-artemis/raw/{{ amq_broker_version }}/artemis-server/src/main/resources/schema/artemis-configuration.xsd"
  server_xsd: "https://github.com/apache/amq_broker-artemis/raw/{{ amq_broker_version }}/artemis-server/src/main/resources/schema/artemis-server.xsd"
  package_list: "{{ amq_broker_base_package_list + [amq_broker_jvm_package] + \
                   ([amq_broker_jmx_exporter_package] if amq_broker_jmx_exporter_enabled else []) + \
                   (['iputils'] if amq_broker_network_check_enabled else []) }}"
  prometheus_package: "{{ 'com.redhat.amq.broker.' if amq_broker_enable is defined and amq_broker_enable and amq_broker_version.split('.')[1] | int >= 11 else 'org.apache.activemq.artemis.' }}"
```
but should be:
```yaml
### internal variables
amq_broker:  # noqa var-naming false positive
  home: "{{ amq_broker_installdir }}"
  user_home: "{{ amq_broker_service_user_home }}"
  version: "{{ amq_broker_version }}"
  download_url: "{{ amq_broker_download_url }}"
  bundle: "{{ amq_broker_archive }}"
  name: "{{ amq_broker_name }}"
  service_name: "{{ amq_broker_service_name }}"
  instance_name: "{{ amq_broker_instance_name }}"
  instance_home: "{{ amq_broker_dest }}/{{ amq_broker_instance_name }}"
  config_xsd: "https://github.com/apache/activemq-artemis/raw/{{ amq_broker_version }}/artemis-server/src/main/resources/schema/artemis-configuration.xsd"
  server_xsd: "https://github.com/apache/activemq-artemis/raw/{{ amq_broker_version }}/artemis-server/src/main/resources/schema/artemis-server.xsd"
  package_list: "{{ amq_broker_base_package_list + [amq_broker_jvm_package] + \
                   ([amq_broker_jmx_exporter_package] if amq_broker_jmx_exporter_enabled else []) + \
                   (['iputils'] if amq_broker_network_check_enabled else []) }}"
  prometheus_package: "{{ 'com.redhat.amq.broker.' if amq_broker_enable is defined and amq_broker_enable and amq_broker_version.split('.')[1] | int >= 11 else 'org.apache.activemq.artemis.' }}"
```

##### ISSUE TYPE
 - Bug Report

##### COLLECTION VERSION
```
redhat.amq_broker                        2.3.0
```

##### EXPECTED RESULTS
Apache Artemis broker (instead of Red Hat Artemis) being installed.

##### ACTUAL RESULTS
Deployment failing
