### ISSUE TITLE
data dir owned by root 

### ISSUE THREAD

**Issue by RobertFloor** [ansible-middleware/amq#34]
Hi we are back to testing the AMQ playbooks. When I run the newest version of the playbook I cannot start since the data directory is owned by root. We are running an NFS mounted dir like this:
```
 sudo mount -t nfs amqtest2.file.core.windows.net:/amqtest2/amqdata /opt/amq/amq-broker/data -o vers=4,minorversion=1,sec=sys
```

This is our playbook:
```
---
- name: Playbook for Red Hat AMQ Broker
  hosts: all
  vars:
    activemq_ha_enabled: true

  collections:
   - middleware_automation.redhat_csp_download
   - middleware_automation.amq
  roles:
   - activemq
```

The problem is that the data dir is owned by root, including the pid file 
```
[azureroot@vm-amq-ansible-1 data]$ ll
total 3
-rw-r--r--. 1 root       root         7 Nov 17 08:17 artemis.pid
drwxr-xr-x. 2 root       root       128 Nov 17 08:18 bindings
drwxr-xr-x. 2 root       root       320 Nov 17 08:18 journal
drwxr-xr-x. 2 root       root        64 Nov 17 08:17 large-messages
drwxr-xr-x. 2 root       root        64 Nov 17 08:17 paging
```
