### ISSUE TITLE
Parameterize prometheus plugin filename

### ISSUE THREAD

**Issue by guidograzioli** [ansible-middleware/amq#44]
##### SUMMARY

The prometheus plugin filename  depends on the install zipfile version, so it needs to be parameterized

```
  block:
    - name: Ensure lib is available to instance
      ansible.builtin.copy:
        src: "{{ activemq.home }}/lib/artemis-prometheus-metrics-plugin-1.1.0.redhat-00002.jar
```

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
n/a
```

##### COLLECTION VERSION

```
1.1.2
```

##### STEPS TO REPRODUCE

```yaml
n/a
```

##### ACTUAL RESULTS

```

```
